/* KIZUNA Microevents: módulo visual aislado. Nunca escribe progreso ni actividad. */
window.KizunaMicroevents=(()=>{
  'use strict';
  const URL='https://vcwqkideizdrhzpbghkj.supabase.co',KEY='sb_publishable_h3pjxT8UPZkYqRhLskVdlA_m-ulI4EF';
  const assetVersion='20260724-confirmation-redesign04';
  ['widgets/kizuna-sealed-envelope.js','widgets/kizuna-focus-camera.js','widgets/kizuna-document-scanner.js','widgets/kizuna-server-link.js','widgets/kizuna-recovery-protocols.js','widgets/kizuna-confirmation-protocols.js'].forEach(src=>{if(!document.querySelector(`script[data-kizuna-widget-src="${src}"]`)){const script=document.createElement('script');script.dataset.kizunaWidgetSrc=src;script.src=`${src}?v=${assetVersion}`;document.head.appendChild(script)}});
  const ids=Array.from({length:14},(_,i)=>`KTB-${String(i+1).padStart(3,'0')}`);
  const events={
    'KTB-001':{r:null,c:['archive','Abrir expediente maestro','Ficha de alta','Incorpora la ficha inicial a la ranura del expediente maestro.']},
    'KTB-002':{r:['hold','Autorizar consulta','Sello de autorización','Mantén presionado para validar el acceso.'],c:['check','Registrar conformidad','Condiciones de custodia','Revisa las cláusulas y registra la conformidad administrativa.']},
    'KTB-003':{r:['slider','Reconstruir correspondencia','Custodia fragmentada','Encaja los fragmentos postales y rompe el sello para recuperar la carta.'],c:['archive','Custodiar correspondencia','Carta personal','Dobla la carta y deposítala en su funda de custodia.']},
    'KTB-004':{r:['dial','Enfocar fotografías','Reconstrucción óptica','Ajusta el dial hasta recuperar la nitidez.'],c:['archive','Incorporar al álbum','Registro fotográfico','Coloca la fotografía recuperada en su página del álbum.']},
    'KTB-005':{r:['beam','Digitalizar informe','Escáner documental','Desplaza el cabezal hasta completar la copia digital.'],c:['slider','Cotejar documento','Original y copia','Superpone ambas versiones y valida su coincidencia.']},
    'KTB-006':{r:['slider','Leer autorización','Lector de credenciales','Desliza la tarjeta por el lector.'],c:['sign','Firmar autorización','Firma autorizada','Registra la firma en la línea indicada.']},
    'KTB-007':{r:['nodes','Conectar nodos','Enlace de archivo','Arrastra el conector hasta el puerto del servidor de destino.'],c:['sync','Aplicar actualización','Línea de versión','Inserta el módulo en la versión vigente del expediente.']},
    'KTB-008':{r:['code','Introducir código','Código de recuperación','Copia el código mostrado por el sistema.'],c:['code','Integrar bloque cifrado','Núcleo documental','Introduce la clave e integra el bloque en el núcleo.']},
    'KTB-009':{r:['surveillance','Rastrear señal','Red de cámaras temporales','Sigue la anomalía y fija los cuatro fotogramas de seguridad.'],c:['archive','Ordenar cronología','Registro temporal','Sitúa la actualización en su posición temporal autorizada.']},
    'KTB-010':{r:['targets','Eliminar corrupción','Limpieza de datos','Localiza y elimina los tres puntos de corrupción.'],c:['slider','Certificar integridad','Escáner de control','Recorre el documento completo para emitir su certificación.']},
    'KTB-011':{r:['rings','Alinear frecuencias','Anillos de recuperación','Alinea los anillos del registro.'],c:['archive','Clasificar documento','Bandejas de archivo','Selecciona la clasificación administrativa correcta.']},
    'KTB-012':{r:['lever','Reanudar sistema','Sistema interrumpido','Activa los módulos siguiendo el protocolo de arranque.'],c:['archive','Cerrar acta','Fechadora central','Introduce el acta y acciona la fechadora del Archivo Central.']},
    'KTB-013':{r:['matrix','Contener anomalía','Matriz de contención temporal','Gira los nodos y conduce la anomalía hasta la cápsula de contención.'],c:['dial','Validar análisis','Bloqueo de validación','Fija los indicadores y gira el bloqueo central.']},
    'KTB-014':{r:['key','Reconstruir sello maestro','Custodia final','Ensambla los fragmentos y activa el sello de cierre.'],c:null}
  };
  const defaults=()=>Object.fromEntries(ids.map(id=>[id,{recovery:Boolean(events[id].r),confirmation:Boolean(events[id].c)}]));
  let settings=defaults(),loaded=false,loading;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const load=()=>loading||(loading=(async()=>{const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),2500);try{const response=await fetch(`${URL}/rest/v1/kizuna_microevent_config?id=eq.1&select=settings`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`},cache:'no-store',signal:controller.signal});if(response.ok){const data=await response.json(),remote=data[0]?.settings||{};ids.forEach(id=>settings[id]={...settings[id],...(remote[id]||{})})}}catch(error){console.warn('Configuración local de microeventos activa.',error)}finally{clearTimeout(timeout);loaded=true}return settings})());
  const play=key=>window.KizunaSound?.play?.(key,{exclusive:true});
  const control=(type,id,phase)=>{const code=String(410+Number(id.slice(-3))*37),number=id.slice(-3);
    if(phase==='confirmation')return `<div class="me-widget-game"><p>COMPLETA EL PROTOCOLO ADMINISTRATIVO DE ${id}</p><kizuna-confirmation-protocol document-id="${id}" data-kizuna-widget="confirmation-protocol"></kizuna-confirmation-protocol></div>`;
    if(type==='hold'&&id==='KTB-002'&&phase==='recovery')return '<div class="me-widget-game"><p>VALIDA LA AUTORIZACIÓN MEDIANTE EL SELLO DE SEGURIDAD</p><kizuna-authorization-seal data-kizuna-widget="authorization-seal"></kizuna-authorization-seal></div>';
    if(type==='hold')return '<button class="me-hold" type="button"><span>SELLO KIZUNA</span><i></i><small>MANTENER</small></button>';
    if(type==='slider'&&id==='KTB-006')return `<div class="me-widget-game"><p>PASA LA CREDENCIAL POR EL LECTOR DE AUTORIZACIÓN</p><kizuna-auth-reader data-kizuna-widget="auth-reader"></kizuna-auth-reader></div>`;
    if(type==='slider'&&id==='KTB-003')return `<div class="me-widget-game"><p>RECONSTRUYE LA CORRESPONDENCIA Y ROMPE EL SELLO DE CUSTODIA</p><kizuna-sealed-envelope data-kizuna-widget="sealed-envelope"></kizuna-sealed-envelope></div>`;
    if(type==='slider')return `<div class="me-direct-game me-envelope-game"><p>TIRA DEL PRECINTO HASTA ROMPER EL SELLO</p><article class="me-sealed-envelope"><div class="me-letter-reveal" aria-hidden="true"><img src="../assets/documents/KTB-003.png" alt=""><small>CARTA RECUPERADA</small></div><span class="me-envelope-flap"></span><i class="me-seal-ribbon"></i><b>KIZUNA / ARCHIVO CIFRADO</b><button type="button" data-drag aria-label="Tirar del precinto hacia la derecha"><span>絆</span><small>TIRAR</small></button></article><section class="me-seal-target" data-drop><i></i><strong>RETIRAR<br>PRECINTO</strong></section></div>`;
    if(type==='archive')return `<div class="me-direct-game me-file-game me-file-${number}"><p>ARRASTRA EL DOCUMENTO HASTA EL ARCHIVADOR</p><article class="me-file-card" data-drag><small>${id}</small><b>${id==='KTB-003'?'CARTA PERSONAL':id==='KTB-009'?'ACTUALIZACIÓN':'DOSSIER RECUPERADO'}</b><em>LECTURA CONFIRMADA</em><i></i></article><section class="me-file-cabinet" data-drop><i></i><strong>${id==='KTB-011'?'EXPEDIENTE MAESTRO':'ARCHIVO CENTRAL'}</strong><small>RANURA ${number}</small></section></div>`;
    if(type==='beam'&&id==='KTB-005')return `<div class="me-widget-game"><p>DESPLAZA EL CABEZAL PARA DIGITALIZAR EL INFORME</p><kizuna-document-scanner data-kizuna-widget="document-scanner"></kizuna-document-scanner></div>`;
    if(type==='beam')return `<div class="me-direct-game me-scanner-game"><p>RECORRE EL DOCUMENTO PARA GENERAR LA COPIA DIGITAL</p><div class="me-scan-workspace"><article class="me-source-report"><header><span>ORIGINAL</span><b>${id}</b></header><img src="../assets/documents/KTB-005.png" alt="Informe original pendiente de digitalización"><button type="button" class="me-scan-head" data-rail aria-label="Desplazar cabezal de escaneo"><i></i><span>SCAN</span></button></article><section class="me-scan-monitor"><header><i></i><span>ARCHIVO DIGITAL</span><b data-meter>0%</b></header><div><img src="../assets/documents/KTB-005.png" alt="Copia digitalizada del informe"></div><strong>PROCESANDO IMAGEN</strong></section></div></div>`;
    if(type==='dial'&&id==='KTB-004')return `<div class="me-widget-game"><p>AJUSTA EL OBJETIVO HASTA RECONSTRUIR LA IMAGEN</p><kizuna-focus-camera data-kizuna-widget="focus-camera"></kizuna-focus-camera></div>`;
    if(type==='surveillance'&&id==='KTB-009'&&phase==='recovery')return '<div class="me-widget-game"><p>SIGUE LA ANOMALÍA ENTRE LAS CÁMARAS Y FIJA LOS FOTOGRAMAS</p><kizuna-vault-lock data-kizuna-widget="vault-lock"></kizuna-vault-lock></div>';
    if(type==='matrix'&&id==='KTB-013'&&phase==='recovery')return '<div class="me-widget-game"><p>RECONFIGURA LA MATRIZ Y CONTÉN LA ANOMALÍA TEMPORAL</p><kizuna-risk-stabilizer data-kizuna-widget="risk-stabilizer"></kizuna-risk-stabilizer></div>';
    if(type==='dial')return `<div class="me-direct-game me-rotary-game me-focus-game"><p>GIRA EL ANILLO DEL OBJETIVO HASTA ENFOCAR LA ESCENA</p><div class="me-camera-viewfinder"><div class="me-photo-preview"><img src="../assets/kyoto-hero.png" alt="Paisaje de Japón pendiente de enfoque"><span class="me-focus-reticle"><i></i><i></i><i></i><i></i></span><small>1/125&nbsp;&nbsp; F4.0&nbsp;&nbsp; ISO 200</small></div><b>RECUPERACIÓN ÓPTICA · JAPÓN</b></div><button type="button" class="me-optic" data-rotary aria-label="Girar anillo de enfoque"><i></i><span>◈</span><small>FOCUS</small></button><strong>ENFOQUE <b data-meter>0%</b></strong></div>`;
    if(type==='rings'&&phase==='recovery')return '<div class="me-widget-game"><p>ALINEA DE FORMA INDEPENDIENTE LOS TRES CANALES TEMPORALES</p><kizuna-frequency-array data-kizuna-widget="frequency-array"></kizuna-frequency-array></div>';
    if(type==='lever'&&phase==='recovery')return '<div class="me-widget-game"><p>REANUDA EL SISTEMA SIGUIENDO EL PROTOCOLO DE ARRANQUE</p><kizuna-power-sequence data-kizuna-widget="power-sequence"></kizuna-power-sequence></div>';
    if(type==='key'&&phase==='recovery')return '<div class="me-widget-game"><p>ENSAMBLA LOS TRES FRAGMENTOS DEL SELLO DE CUSTODIA</p><kizuna-closure-key data-kizuna-widget="closure-key"></kizuna-closure-key></div>';
    if(type==='check')return '<div class="me-consent-game"><label class="me-check"><input type="checkbox"><i>✓</i><span>He revisado el documento y comprendo las condiciones de custodia.</span></label><button type="button" data-consent disabled>REGISTRAR CONFORMIDAD</button></div>';
    if(type==='stamp')return `<div class="me-direct-game me-stamping-game me-stamp-${number}"><p>ARRASTRA EL SELLO SOBRE EL ÁREA MARCADA</p><button class="me-hand-stamp" type="button" data-drag><i></i><span>${id==='KTB-004'?'ÁLBUM':id==='KTB-005'?'REVISADO':id==='KTB-010'?'ÍNTEGRO':'VALIDADO'}</span></button><article class="me-stamp-document" data-drop><small>${id==='KTB-004'?'REGISTRO FOTOGRÁFICO':id==='KTB-005'?'INFORME DE MISIÓN':id==='KTB-010'?'CONTROL DE INTEGRIDAD':'ANÁLISIS DE RIESGO'}</small><i></i><i></i><i></i><span>APLICAR AQUÍ</span></article></div>`;
    if(type==='sign')return `<div class="me-sign-game"><p>DIBUJA UNA FIRMA SOBRE LA LÍNEA</p><section class="me-sign-sheet"><small>${id==='KTB-006'?'AUTORIZACIÓN DE CONSULTA':'ACTA DE REANUDACIÓN'}</small><canvas width="620" height="150" data-sign aria-label="Área de firma"></canvas><b>FIRMA DEL DESTINATARIO</b></section><button type="button" data-sign-confirm disabled>REGISTRAR FIRMA</button></div>`;
    if(type==='sync')return '<div class="me-direct-game me-sync-game"><p>ARRASTRA EL PAQUETE AL ARCHIVO CENTRAL</p><button type="button" class="me-data-packet" data-drag><i></i><strong>UPDATE</strong><small>KTB-007</small></button><section class="me-central-node" data-drop><i></i><strong>ARCHIVO CENTRAL</strong></section><span class="me-sync-line"></span></div>';
    if(type==='nodes'&&id==='KTB-007')return '<div class="me-widget-game"><p>CONECTA FÍSICAMENTE LOS NODOS DEL ARCHIVO</p><kizuna-server-link data-kizuna-widget="server-link"></kizuna-server-link></div>';
    if(type==='nodes')return '<div class="me-network-game"><p>CONECTA FÍSICAMENTE LOS DOS SERVIDORES DEL ARCHIVO</p><svg viewBox="0 0 700 300" aria-hidden="true"><path class="me-network-grid" d="M25 55H675M25 150H675M25 245H675M115 25V275M235 25V275M350 25V275M465 25V275M585 25V275"/><path class="me-network-path" data-cable d="M205 224 C285 282 415 282 497 224"/></svg><section class="me-server-node me-server-a"><header><i></i><span>KYOTO-NODE-07</span><small>ONLINE</small></header><div class="me-server-rack"><span><i></i><i></i><b></b><em>ARCHIVE 01</em></span><span><i></i><i></i><b></b><em>DATA CORE</em></span><span><i></i><i></i><b></b><em>UPLINK</em></span></div><footer>PUERTO DE ORIGEN <i class="me-server-port"></i></footer></section><div class="me-cable-origin"><i></i></div><button type="button" class="me-server-plug" data-drag aria-label="Arrastrar conector RJ45 al servidor de destino"><i></i><span>RJ45</span></button><section class="me-server-node me-server-b" data-drop><header><i></i><span>TOKYO-ARCHIVE-03</span><small>WAITING</small></header><div class="me-server-rack"><span><i></i><i></i><b></b><em>ARCHIVE 02</em></span><span><i></i><i></i><b></b><em>SECURE DATA</em></span><span><i></i><i></i><b></b><em>UPLINK</em></span></div><footer>PUERTO DE DESTINO <i class="me-server-port"></i></footer></section></div>';
    if(type==='code'&&id==='KTB-008'&&phase==='recovery')return '<div class="me-widget-game"><p>REPLICA LA SECUENCIA EN LA CONSOLA CIFRADA</p><kizuna-code-terminal data-kizuna-widget="code-terminal"></kizuna-code-terminal></div>';
    if(type==='code')return `<div class="me-code me-code-${phase}"><header><span>${phase==='recovery'?'TRANSMISIÓN INTERCEPTADA':'REGISTRO DE INTEGRACIÓN'}</span><i></i><i></i><i></i></header><p>CLAVE <strong>${code}</strong></p><label><small>INTRODUCIR SECUENCIA</small><input inputmode="numeric" maxlength="3" placeholder="000" data-code="${code}" aria-label="Código"></label></div>`;
    if(type==='targets'&&phase==='recovery')return '<div class="me-widget-game"><p>ELIMINA LAS TRES FIRMAS MALICIOSAS DEL DOCUMENTO</p><kizuna-corruption-cleaner data-kizuna-widget="corruption-cleaner"></kizuna-corruption-cleaner></div>';
    return '<button class="me-stamp" type="button"><span>CONTINUAR</span></button>';
  };
  const bind=(root,finish)=>{let done=false;const complete=()=>{if(done)return;done=true;root.classList.add('is-complete');play('recovery_step');setTimeout(finish,720)};
    const widget=root.querySelector('[data-kizuna-widget]');if(widget){widget.addEventListener('kizuna:complete',complete,{once:true});widget.addEventListener('kizuna:progress',event=>root.style.setProperty('--me-widget-progress',`${event.detail?.value||0}%`));}
    const drag=root.querySelector('[data-drag]'),drop=root.querySelector('[data-drop]');if(drag&&drop){let startX=0,startY=0,x=0,y=0;const reset=()=>{x=0;y=0;drag.style.transform='';drag.classList.remove('is-dragging');root.classList.remove('me-drag-active')};drag.onpointerdown=event=>{if(done)return;event.preventDefault();startX=event.clientX-x;startY=event.clientY-y;drag.setPointerCapture?.(event.pointerId);drag.classList.add('is-dragging');root.classList.add('me-drag-active')};drag.onpointermove=event=>{if(!drag.classList.contains('is-dragging'))return;x=event.clientX-startX;y=event.clientY-startY;drag.style.transform=`translate3d(${x}px,${y}px,0)`;const a=drag.getBoundingClientRect(),b=drop.getBoundingClientRect(),inside=a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;drop.classList.toggle('is-hovered',inside)};const release=()=>{if(!drag.classList.contains('is-dragging'))return;const a=drag.getBoundingClientRect(),b=drop.getBoundingClientRect(),inside=a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;drop.classList.remove('is-hovered');if(inside){drag.classList.remove('is-dragging');root.classList.add('me-drop-success');complete()}else reset()};drag.onpointerup=drag.onpointercancel=release}
    const rotary=root.querySelector('[data-rotary]');if(rotary){let active=false,last=0,lastX=0,lastY=0,total=0;const isFocus=root.classList.contains('me-focus-game');const angle=event=>{const rect=rotary.getBoundingClientRect();return Math.atan2(event.clientY-(rect.top+rect.height/2),event.clientX-(rect.left+rect.width/2))*180/Math.PI};rotary.onpointerdown=event=>{event.preventDefault();active=true;last=angle(event);lastX=event.clientX;lastY=event.clientY;rotary.setPointerCapture?.(event.pointerId);rotary.classList.add('is-turning')};rotary.onpointermove=event=>{if(!active)return;event.preventDefault();let delta;if(isFocus){delta=Math.hypot(event.clientX-lastX,event.clientY-lastY)*1.45;lastX=event.clientX;lastY=event.clientY}else{const current=angle(event);delta=current-last;if(delta>180)delta-=360;if(delta<-180)delta+=360;last=current}total=Math.max(0,total+delta);const progress=Math.min(100,total/2.4);root.style.setProperty('--me-turn',`${total}deg`);root.style.setProperty('--me-turn-reverse',`${total*-1}deg`);root.style.setProperty('--me-turn-soft',`${Math.min(115,total*.48)}deg`);root.querySelector('[data-meter]')?.replaceChildren(`${Math.round(progress)}%`);root.classList.toggle('me-halfway',progress>=48);if(progress>=(isFocus?100:92))complete()};const stop=()=>{active=false;rotary.classList.remove('is-turning')};rotary.onpointerup=rotary.onpointercancel=stop}
    const rail=root.querySelector('[data-rail]');if(rail){let active=false,start=0,travel=0;rail.onpointerdown=event=>{event.preventDefault();active=true;start=event.clientX;travel=0;rail.setPointerCapture?.(event.pointerId);rail.classList.add('is-scanning')};rail.onpointermove=event=>{if(!active)return;const max=Math.max(120,rail.parentElement.clientWidth-100);travel=Math.max(0,Math.min(max,event.clientX-start));const progress=travel/max*100;rail.style.transform=`translateX(${travel}px)`;root.style.setProperty('--me-scan',`${progress}%`);root.querySelector('[data-meter]')?.replaceChildren(`${Math.round(progress)}%`);if(progress>88)complete()};rail.onpointerup=rail.onpointercancel=()=>{active=false;rail.classList.remove('is-scanning');if(!done){rail.style.transform='';root.style.setProperty('--me-scan','0%');root.querySelector('[data-meter]')?.replaceChildren('0%')}}}
    if(rotary&&root.classList.contains('me-focus-game')){const move=rotary.onpointermove;rotary.onpointermove=event=>{move(event);const progress=parseFloat(root.querySelector('[data-meter]')?.textContent)||0;root.style.setProperty('--me-blur',`${Math.max(0,8-progress*.08)}px`)}}
    const frequencyRings=[...root.querySelectorAll('[data-frequency-ring]')];if(frequencyRings.length){const normalize=value=>((value%360)+360)%360;const distance=value=>Math.min(normalize(value),360-normalize(value));const update=()=>{const aligned=frequencyRings.filter(ring=>ring.classList.contains('is-aligned')).length,progress=Math.round(aligned/frequencyRings.length*100);root.querySelector('[data-meter]')?.replaceChildren(`${progress}%`);root.querySelector('[data-frequency-status]')?.replaceChildren(aligned===frequencyRings.length?'SEÑAL SINCRONIZADA':`SEÑAL INESTABLE · ${aligned}/3`);root.classList.toggle('me-frequency-partial',aligned>0);if(aligned===frequencyRings.length)complete()};frequencyRings.forEach(ring=>{let active=false,lastAngle=0,current=Number(ring.dataset.angle)||0;const pointerAngle=event=>{const rect=ring.getBoundingClientRect();return Math.atan2(event.clientY-(rect.top+rect.height/2),event.clientX-(rect.left+rect.width/2))*180/Math.PI};const paint=()=>{ring.style.setProperty('--frequency-angle',`${current}deg`);ring.classList.toggle('is-near',distance(current)<28)};paint();ring.onpointerdown=event=>{if(ring.classList.contains('is-aligned'))return;event.preventDefault();active=true;lastAngle=pointerAngle(event);ring.setPointerCapture?.(event.pointerId);ring.classList.add('is-turning')};ring.onpointermove=event=>{if(!active)return;event.preventDefault();const next=pointerAngle(event);let delta=next-lastAngle;if(delta>180)delta-=360;if(delta<-180)delta+=360;current=normalize(current+delta);lastAngle=next;paint()};const stop=()=>{if(!active)return;active=false;ring.classList.remove('is-turning');if(distance(current)<16){current=0;ring.classList.add('is-aligned');paint();play('recovery_step')}update()};ring.onpointerup=ring.onpointercancel=stop});update()}
    const breakers=[...root.querySelectorAll('[data-breaker]')];if(breakers.length){let expected=1,locked=false;const status=root.querySelector('[data-power-status]'),message=root.querySelector('[data-power-message]');const reset=()=>{breakers.forEach(button=>{button.classList.remove('is-on','is-error');button.disabled=false});root.classList.remove('me-power-failure');expected=1;status?.replaceChildren('OFFLINE · PASO 0/4');message?.replaceChildren('ESPERANDO SECUENCIA DE ARRANQUE');locked=false};breakers.forEach(button=>button.onclick=()=>{if(locked||button.classList.contains('is-on'))return;const order=Number(button.dataset.breaker);if(order!==expected){locked=true;button.classList.add('is-error');root.classList.add('me-power-failure');status?.replaceChildren('ERROR · ORDEN INCORRECTO');message?.replaceChildren('FALLO DE ARRANQUE · REINICIANDO MÓDULOS');setTimeout(reset,780);return}button.classList.add('is-on');button.disabled=true;play('recovery_step');root.style.setProperty('--me-power-step',expected);status?.replaceChildren(`ARRANQUE · PASO ${expected}/4`);message?.replaceChildren(expected===4?'SECUENCIA CORRECTA · SISTEMA EN LÍNEA':`MÓDULO ${button.querySelector('small')?.textContent||expected} ACTIVADO`);expected++;if(expected===5){locked=true;root.classList.add('me-power-online');setTimeout(complete,420)}})}
    const hold=root.querySelector('.me-hold');if(hold){let timer;const stop=()=>{clearTimeout(timer);hold.classList.remove('is-holding')};hold.onpointerdown=()=>{hold.classList.add('is-holding');timer=setTimeout(complete,1200)};hold.onpointerup=hold.onpointerleave=hold.onpointercancel=stop}
    const check=root.querySelector('.me-check input'),consent=root.querySelector('[data-consent]');if(check&&consent){check.onchange=()=>consent.disabled=!check.checked;consent.onclick=complete}else if(check)check.onchange=()=>check.checked&&complete();
    const canvas=root.querySelector('[data-sign]'),signConfirm=root.querySelector('[data-sign-confirm]');if(canvas&&signConfirm){const context=canvas.getContext('2d');let drawing=false,lastX=0,lastY=0,distance=0;context.strokeStyle='#8f1d1a';context.lineWidth=4;context.lineCap='round';const point=event=>{const rect=canvas.getBoundingClientRect();return[(event.clientX-rect.left)*canvas.width/rect.width,(event.clientY-rect.top)*canvas.height/rect.height]};canvas.onpointerdown=event=>{event.preventDefault();drawing=true;[lastX,lastY]=point(event);canvas.setPointerCapture?.(event.pointerId)};canvas.onpointermove=event=>{if(!drawing)return;const [x,y]=point(event);context.beginPath();context.moveTo(lastX,lastY);context.lineTo(x,y);context.stroke();distance+=Math.hypot(x-lastX,y-lastY);lastX=x;lastY=y;if(distance>160)signConfirm.disabled=false};canvas.onpointerup=canvas.onpointercancel=()=>drawing=false;signConfirm.onclick=complete}
    root.querySelectorAll('.me-stamp,.me-sign,.me-sync,.me-stamp-console,.me-sign-console,.me-sync-console').forEach(button=>button.onclick=complete);
    const nodes=[...root.querySelectorAll('[data-node]')];nodes.forEach(button=>button.onclick=()=>{button.classList.add('active');if(nodes.every(node=>node.classList.contains('active')))complete()});
    const code=root.querySelector('[data-code]');if(code)code.oninput=()=>{code.classList.toggle('is-error',code.value.length===3&&code.value!==code.dataset.code);if(code.value===code.dataset.code)complete()};
    const targets=[...root.querySelectorAll('.me-targets button')];targets.forEach(button=>button.onclick=()=>{button.disabled=true;if(targets.every(item=>item.disabled))complete()});
    root.querySelector('[data-me-assist]').onclick=complete;setTimeout(()=>!done&&root.classList.add('show-assist'),1100);setTimeout(()=>!done&&root.classList.add('show-assist'),6500);
  };
  const run=async(id,phase,{container,force=false}={})=>{try{if(!loaded)await load();const key=phase==='recovery'?'r':'c',item=events[id]?.[key];if(!item||(!force&&settings[id]?.[phase]===false)||!container)return true;return await new Promise(resolve=>{const [type,action,title,instruction]=item;container.innerHTML=`<section class="kizuna-microevent me-${phase}" data-kind="${type}" data-document="${id}" data-phase="${phase}" aria-live="polite"><header><div><p>${phase==='recovery'?'OPERACIÓN DE RECUPERACIÓN':'ACCIÓN ADMINISTRATIVA'}</p><h3>${id}</h3></div><span>${phase==='recovery'?'SISTEMA KIZUNA':'REGISTRO DE LECTURA'}<strong>${String(+id.slice(-3)).padStart(2,'0')}</strong></span></header><div class="me-stage"><p class="me-kicker">${esc(title)}</p><h4>${esc(action)}</h4><p class="me-instruction">${esc(instruction)}</p>${control(type,id,phase)}<p class="me-completed"><b>✓</b> Operación completada</p></div><footer><span>La asistencia automática evita bloqueos.</span><button type="button" data-me-assist>Completar automáticamente</button></footer></section>`;const root=container.querySelector('.kizuna-microevent');play(phase==='recovery'?'recovery_step':'reading_confirmed');bind(root,()=>resolve(true))})}catch(error){console.warn('Microevento omitido de forma segura.',error);return true}};
  const preview=(id,phase)=>{const overlay=document.createElement('div');overlay.className='admin-me-preview';overlay.innerHTML=`<section role="dialog" aria-modal="true" aria-label="Prueba de ${id}"><header><div><span>VISTA DE PRUEBA</span><strong>${id} · ${phase==='recovery'?'RECUPERACIÓN':'CONFIRMACIÓN'}</strong></div><button type="button" data-me-close aria-label="Cerrar prueba">×</button></header><div class="admin-me-preview-stage"></div><footer><span>Esta prueba no modifica el expediente ni registra actividad.</span><button type="button" data-me-close>Cerrar prueba</button></footer></section>`;document.body.appendChild(overlay);document.body.classList.add('admin-me-preview-open');const close=()=>{overlay.remove();document.body.classList.remove('admin-me-preview-open')};overlay.querySelectorAll('[data-me-close]').forEach(button=>button.onclick=close);overlay.onclick=event=>{if(event.target===overlay)close()};run(id,phase,{container:overlay.querySelector('.admin-me-preview-stage'),force:true}).then(()=>{if(overlay.isConnected)overlay.classList.add('is-tested')})};
  const createAdmin=()=>{const nav=document.createElement('button');nav.type='button';nav.dataset.adminView='microevents';nav.innerHTML='<span>09</span>Interacciones';const view=document.createElement('section');view.id='admin-microevents-view';view.className='admin-view';view.hidden=true;view.innerHTML='<p class="system-line">ARCHIVO CENTRAL · EXPERIENCIA INTERACTIVA</p><h1>Microeventos del<br><em>expediente.</em></h1><p class="admin-intro">Configura por separado la recuperación y la confirmación de cada documento KTB.</p><section class="admin-me-card"><header><div><p class="system-line">CONFIGURACIÓN POR DOCUMENTO</p><h2>Interacciones de lectura</h2></div><div><button type="button" data-me-all="on">Activar compatibles</button><button type="button" data-me-all="off">Desactivar todos</button></div></header><div id="admin-me-list"><p>Cargando…</p></div><footer><span id="admin-me-status"></span><button id="admin-me-save" type="button">Guardar configuración</button></footer></section>';return{nav,view}};
  const renderAdmin=async view=>{await load();const list=view.querySelector('#admin-me-list');list.innerHTML=ids.map(id=>`<article class="admin-me-row"><div><strong>${id}</strong><span>${id==='KTB-014'?'Cierre especial':'Secuencia principal'}</span></div>${['recovery','confirmation'].map((phase,index)=>{const item=events[id][index?'c':'r'],isRecovery=phase==='recovery',phaseLabel=isRecovery?'Recuperación':'Confirmación';return `<div class="admin-me-option is-${phase}"><label class="admin-me-switch ${item?'':'is-unavailable'}"><input type="checkbox" data-id="${id}" data-phase="${phase}" ${settings[id][phase]?'checked':''} ${item?'':'disabled'}><i></i><span>${phaseLabel}<small>${item?item[1]:isRecovery?'Tutorial sin mecánica':'Conserva el cierre actual'}</small></span></label>${item?`<button type="button" class="admin-me-test admin-me-test--${phase}" data-me-test="${id}" data-me-phase="${phase}" aria-label="Probar ${phaseLabel.toLowerCase()} de ${id}"><span aria-hidden="true">${isRecovery?'↻':'✓'}</span><b>Probar</b><small>${phaseLabel}</small></button>`:''}</div>`}).join('')}</article>`).join('');list.querySelectorAll('input[data-id]').forEach(input=>input.onchange=()=>settings[input.dataset.id][input.dataset.phase]=input.checked);list.querySelectorAll('[data-me-test]').forEach(button=>button.onclick=()=>preview(button.dataset.meTest,button.dataset.mePhase));view.querySelectorAll('[data-me-all]').forEach(button=>button.onclick=()=>list.querySelectorAll('input:not(:disabled)').forEach(input=>{input.checked=button.dataset.meAll==='on';settings[input.dataset.id][input.dataset.phase]=input.checked}));view.querySelector('#admin-me-save').onclick=async()=>{const status=view.querySelector('#admin-me-status'),button=view.querySelector('#admin-me-save');button.disabled=true;status.textContent='Guardando…';try{if(!window.supabase)throw Error('Supabase no disponible');const client=window.supabase.createClient(URL,KEY),{error}=await client.from('kizuna_microevent_config').upsert({id:1,settings,updated_at:new Date().toISOString()});if(error)throw error;status.textContent='Configuración guardada.'}catch(error){console.error(error);status.textContent='Ejecuta primero supabase-microevent-config.sql.'}finally{button.disabled=false}}};
  const confirmationEnabled=async id=>{await load();return Boolean(events[id]?.c&&settings[id]?.confirmation!==false)};
  const labelFor=id=>loaded&&settings[id]?.confirmation===false?'Confirmar lectura':events[id]?.c?.[1]||(id==='KTB-014'?'Finalizar expediente':'Confirmar lectura');
  return{runRecovery:(id,o)=>run(id,'recovery',o),runConfirmation:(id,o)=>run(id,'confirmation',o),confirmationEnabled,labelFor,createAdmin,renderAdmin};
})();
