(()=>{
const openButton=document.querySelector('#quiz-open');
if(!openButton)return;

const questions=[
  {type:'visual',label:'PREGUNTA VISUAL · GASTRONOMÍA',title:'¿Qué plato japonés aparece representado?',visual:'ramen',options:['Udon','Ramen','Soba','Sukiyaki'],answer:1,explanation:'El ramen combina fideos de trigo con caldo y distintos acompañamientos.'},
  {type:'choice',label:'HISTORIA · OPCIÓN MÚLTIPLE',title:'¿Qué acontecimiento marcó el comienzo de la era Meiji en 1868?',options:['La apertura de Tokio Disneyland','La Restauración Meiji','La construcción del Shinkansen','El inicio del período Edo'],answer:1,explanation:'La Restauración Meiji devolvió el poder político al emperador e inició una profunda modernización.'},
  {type:'choice',label:'SITUACIÓN · METRO',title:'Tu teléfono suena dentro de un vagón tranquilo. ¿Qué deberías hacer?',options:['Responder en voz baja','Ponerlo en silencio y esperar para hablar','Salir corriendo del vagón','Subir el volumen para oír mejor'],answer:1,explanation:'En el transporte japonés se evita hablar por teléfono y se mantiene el móvil en silencio.'},
  {type:'boolean',label:'VERDADERO O FALSO · HISTORIA',title:'Las geishas son artistas profesionales formadas en música, danza y conversación.',options:['Verdadero','Falso'],answer:0,explanation:'Su oficio está vinculado a las artes tradicionales y al entretenimiento, no a los mitos populares.'},
  {type:'choice',label:'IDIOMA · TRADUCCIÓN',title:'¿Cómo pedirías agua educadamente en un restaurante?',options:['O-mizu o kudasai','O-cha wa doko desu ka','Itadakimasu','O-kaikei onegaishimasu'],answer:0,explanation:'「お水をください」(O-mizu o kudasai) significa “Agua, por favor”.'},
  {type:'match',label:'EMPAREJAMIENTO · DESTINOS',title:'Empareja cada ciudad con su lugar más representativo.',pairs:[['Kioto','Fushimi Inari'],['Nara','Tōdai-ji'],['Hiroshima','Parque Conmemorativo de la Paz']],choices:['Parque Conmemorativo de la Paz','Fushimi Inari','Tōdai-ji'],explanation:'Cada destino conserva una parte distinta de la memoria cultural de Japón.'},
  {type:'choice',label:'ESCENARIO · ORIENTACIÓN',title:'Te has perdido en una gran estación. ¿Cuál es la mejor opción?',options:['Seguir a cualquier grupo','Preguntar al personal mostrando tu destino','Subir al primer tren que llegue','Esperar sin pedir ayuda'],answer:1,explanation:'El personal de estación puede indicarte la línea, el andén y el trayecto correcto.'},
  {type:'choice',label:'IDIOMA · CORTESÍA',title:'Conoces a alguien por primera vez. ¿Qué saludo resulta más adecuado?',options:['Hajimemashite. Yoroshiku onegaishimasu.','Sayonara!','Oyasuminasai.','Tadaima!'],answer:0,explanation:'Es una fórmula habitual y cortés al presentarse por primera vez.'},
  {type:'order',label:'ORDENAMIENTO · RAMEN',title:'Ordena los pasos habituales en un local de ramen con máquina de tickets.',steps:['Esperar tu turno en la fila','Elegir y pagar en la máquina','Entregar el ticket al personal','Sentarte en el lugar indicado'],answer:['Esperar tu turno en la fila','Elegir y pagar en la máquina','Entregar el ticket al personal','Sentarte en el lugar indicado'],explanation:'En muchos locales primero se compra un ticket y después se entrega al personal.'},
  {type:'visual',label:'PREGUNTA VISUAL · ARQUITECTURA',title:'¿Cómo se llama esta puerta tradicional japonesa?',visual:'torii',options:['Pagoda','Torii','Tenshu','Minka'],answer:1,explanation:'Un torii marca simbólicamente la entrada a un espacio sagrado sintoísta.'}
];

let dialog,index=0,score=0,locked=false,selectedOrder=[];
const escape=value=>String(value).replace(/[&<>'"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));
const audio=(correct)=>{try{const Context=window.AudioContext||window.webkitAudioContext;if(!Context)return;const context=new Context(),gain=context.createGain();gain.connect(context.destination);gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(.12,context.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.48);(correct?[659.25,783.99,987.77]:[220,174.61]).forEach((frequency,i)=>{const oscillator=context.createOscillator();oscillator.type=correct?'sine':'triangle';oscillator.frequency.value=frequency;oscillator.connect(gain);oscillator.start(context.currentTime+i*.11);oscillator.stop(context.currentTime+.42+i*.11)});setTimeout(()=>context.close(),900)}catch(error){console.warn('No se pudo reproducir el sonido del quiz.',error)}};
const progress=()=>Math.round(index/questions.length*100);
const visualMarkup=visual=>visual==='ramen'?'<div class="quiz-ramen" aria-label="Cuenco de fideos japoneses"><span class="quiz-steam">〰 〰 〰</span><strong>🍜</strong><small>PLATO 01 · IDENTIFICACIÓN</small></div>':'<figure class="quiz-torii"><img src="assets/documents/AR-03/Templos/001-Fushimi Inari.png" alt="Puertas rojas de un santuario japonés"><figcaption>ARCHIVO VISUAL · KIOTO</figcaption></figure>';
const optionsMarkup=question=>`<div class="quiz-options">${question.options.map((option,optionIndex)=>`<button type="button" data-answer="${optionIndex}"><span>${String.fromCharCode(65+optionIndex)}</span>${escape(option)}</button>`).join('')}</div>`;
const matchMarkup=question=>`<div class="quiz-matches">${question.pairs.map(([city])=>`<label><strong>${escape(city)}</strong><select data-match="${escape(city)}"><option value="">Selecciona un lugar…</option>${question.choices.map(choice=>`<option>${escape(choice)}</option>`).join('')}</select></label>`).join('')}</div><button class="quiz-submit-special" type="button" data-submit-match>Comprobar parejas →</button>`;
const orderMarkup=question=>`<p class="quiz-order-help">Pulsa los pasos en el orden correcto.</p><div class="quiz-order-pool">${question.steps.slice().sort(()=>.5-Math.random()).map(step=>`<button type="button" data-order-step="${escape(step)}">${escape(step)}</button>`).join('')}</div><ol class="quiz-order-selection" aria-live="polite"></ol><div class="quiz-order-actions"><button type="button" data-reset-order>Reiniciar</button><button class="quiz-submit-special" type="button" data-submit-order disabled>Comprobar orden →</button></div>`;

const render=()=>{
  const question=questions[index];locked=false;selectedOrder=[];
  dialog.querySelector('.quiz-progress span').style.width=`${progress()}%`;
  dialog.querySelector('.quiz-count').textContent=`RETO ${String(index+1).padStart(2,'0')} / ${questions.length}`;
  dialog.querySelector('.quiz-score strong').textContent=score;
  const content=dialog.querySelector('.quiz-content');
  content.innerHTML=`<div class="quiz-question-enter"><p class="quiz-type">${question.label}</p><h2 id="quiz-title">${question.title}</h2>${question.visual?visualMarkup(question.visual):''}${question.type==='match'?matchMarkup(question):question.type==='order'?orderMarkup(question):optionsMarkup(question)}<div class="quiz-feedback" role="status" aria-live="polite"></div></div>`;
  content.querySelectorAll('[data-answer]').forEach(button=>button.addEventListener('click',()=>answerChoice(Number(button.dataset.answer),button)));
  content.querySelector('[data-submit-match]')?.addEventListener('click',answerMatch);
  content.querySelectorAll('[data-order-step]').forEach(button=>button.addEventListener('click',()=>selectOrderStep(button)));
  content.querySelector('[data-reset-order]')?.addEventListener('click',()=>render());
  content.querySelector('[data-submit-order]')?.addEventListener('click',answerOrder);
};

const finishAnswer=(correct,explanation)=>{
  if(locked)return;locked=true;if(correct)score+=100;audio(correct);
  dialog.querySelector('.quiz-score strong').textContent=score;
  dialog.classList.remove('is-correct','is-wrong');void dialog.offsetWidth;dialog.classList.add(correct?'is-correct':'is-wrong');
  if(correct)confetti();
  const feedback=dialog.querySelector('.quiz-feedback');
  feedback.className=`quiz-feedback ${correct?'correct':'wrong'}`;
  feedback.innerHTML=`<div><strong>${correct?'Respuesta correcta':'No exactamente'}</strong><p>${escape(explanation)}</p></div><button type="button">${index===questions.length-1?'Ver resultado':'Siguiente reto'} →</button>`;
  feedback.querySelector('button').focus();feedback.querySelector('button').onclick=()=>{index++;index>=questions.length?renderResult():render()};
};
const answerChoice=(answer,button)=>{if(locked)return;const question=questions[index],correct=answer===question.answer;dialog.querySelectorAll('[data-answer]').forEach(item=>{item.disabled=true;if(Number(item.dataset.answer)===question.answer)item.classList.add('is-answer')});button.classList.add(correct?'is-selected-correct':'is-selected-wrong');finishAnswer(correct,question.explanation)};
const answerMatch=()=>{if(locked)return;const question=questions[index],values=[...dialog.querySelectorAll('[data-match]')];if(values.some(select=>!select.value)){dialog.querySelector('.quiz-feedback').textContent='Completa las tres parejas antes de comprobar.';return}const correct=values.every(select=>question.pairs.find(([city])=>city===select.dataset.match)?.[1]===select.value);values.forEach(select=>{select.disabled=true;const expected=question.pairs.find(([city])=>city===select.dataset.match)?.[1];select.parentElement.classList.add(select.value===expected?'is-match-correct':'is-match-wrong')});finishAnswer(correct,question.explanation)};
const selectOrderStep=button=>{if(locked||button.disabled)return;selectedOrder.push(button.dataset.orderStep);button.disabled=true;const list=dialog.querySelector('.quiz-order-selection'),item=document.createElement('li');item.textContent=button.dataset.orderStep;list.appendChild(item);dialog.querySelector('[data-submit-order]').disabled=selectedOrder.length!==questions[index].steps.length};
const answerOrder=()=>{if(locked)return;const question=questions[index],correct=question.answer.every((step,i)=>selectedOrder[i]===step);dialog.querySelectorAll('[data-order-step],[data-submit-order],[data-reset-order]').forEach(button=>button.disabled=true);finishAnswer(correct,question.explanation)};
const confetti=()=>{const layer=dialog.querySelector('.quiz-confetti');for(let i=0;i<24;i++){const piece=document.createElement('i');piece.style.setProperty('--x',`${Math.random()*100}%`);piece.style.setProperty('--delay',`${Math.random()*.25}s`);piece.style.setProperty('--color',['#861816','#d9b769','#142b25','#f5f0e7'][i%4]);layer.appendChild(piece);setTimeout(()=>piece.remove(),1400)}};
const renderResult=()=>{const rank=score>=900?'Maestro del viaje':score>=700?'Viajero experto':score>=500?'Explorador de Japón':'Aprendiz de viajero';dialog.querySelector('.quiz-progress span').style.width='100%';dialog.querySelector('.quiz-count').textContent='EXPEDICIÓN COMPLETADA';dialog.querySelector('.quiz-content').innerHTML=`<section class="quiz-result"><img src="assets/kizuna-logo-official.png" alt=""><p>RESULTADO DEL ARCHIVO CULTURAL</p><h2>${rank}</h2><div class="quiz-result-score"><strong>${score}</strong><span>puntos de 1000</span></div><p>Has completado los diez retos sobre cultura, idioma y costumbres de Japón.</p><div><button type="button" data-restart>Repetir quiz</button><button type="button" data-close-result>Cerrar</button></div></section>`;dialog.querySelector('[data-restart]').onclick=()=>{index=0;score=0;render()};dialog.querySelector('[data-close-result]').onclick=closeQuiz};
const closeQuiz=()=>{dialog?.close();dialog?.remove();dialog=null;document.body.classList.remove('quiz-open')};
const openQuiz=event=>{event.preventDefault();document.querySelector('#kizuna-quiz')?.remove();dialog=document.createElement('dialog');dialog.id='kizuna-quiz';dialog.setAttribute('aria-labelledby','quiz-title');dialog.innerHTML='<div class="quiz-shell"><header><div><span>ARCHIVO CULTURAL INTERACTIVO</span><strong>QUIZ · JAPÓN</strong></div><div class="quiz-score">PUNTOS <strong>0</strong></div><button type="button" class="quiz-close" aria-label="Cerrar quiz">×</button></header><div class="quiz-status"><span class="quiz-count">RETO 01 / 10</span><div class="quiz-progress"><span></span></div></div><main class="quiz-content"></main><div class="quiz-confetti" aria-hidden="true"></div></div>';document.body.appendChild(dialog);dialog.querySelector('.quiz-close').onclick=closeQuiz;dialog.addEventListener('cancel',event=>{event.preventDefault();closeQuiz()});dialog.addEventListener('click',event=>{if(event.target===dialog)closeQuiz()});index=0;score=0;document.body.classList.add('quiz-open');dialog.showModal();render()};
openButton.addEventListener('click',openQuiz);
})();
