if(!window.kizunaStorage){const storageAssetsScript=document.createElement('script');storageAssetsScript.src='storage-assets.js';document.head.appendChild(storageAssetsScript)}
const header=document.querySelector('.site-header');document.querySelector('.menu-toggle').addEventListener('click',()=>header.classList.toggle('open'));if(localStorage.getItem('kizuna-complete'))document.querySelector('footer p').textContent='Gracias por haber preservado este recuerdo.';
let publicSupabaseClient=null,publicProgressState=null,publicUser=null;
let publicSupabasePromise=null;
const getPublicSupabase=async()=>{if(publicSupabaseClient)return publicSupabaseClient;if(!publicSupabasePromise)publicSupabasePromise=(async()=>{if(!window.supabase)await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';script.onload=resolve;script.onerror=reject;document.head.appendChild(script)});publicSupabaseClient=window.supabase.createClient('https://vcwqkideizdrhzpbghkj.supabase.co','sb_publishable_h3pjxT8UPZkYqRhLskVdlA_m-ulI4EF');return publicSupabaseClient})();return publicSupabasePromise};
const publicSession=document.createElement('div');publicSession.id='public-session';publicSession.setAttribute('aria-live','polite');header.insertBefore(publicSession,document.querySelector('.menu-toggle'));
const clearPublicSession=()=>{publicUser=null;publicProgressState=null;publicSession.classList.remove('active');publicSession.innerHTML='';document.querySelector('#alberto-message-prompt')?.remove();document.querySelector('#alberto-message-link')?.remove();document.querySelector('#alberto-letter')?.remove();document.querySelectorAll('.expedient-link').forEach(link=>link.textContent='Acceso al Expediente');document.querySelector('footer p').textContent='Because the best memories deserve to exist.'};
const publicEscape=value=>String(value).replace(/[&<>'"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));
const showPublicSession=(user,profile)=>{const displayName=profile?.display_name||user.user_metadata?.display_name||user.email?.split('@')[0]||'Usuario autorizado';publicSession.classList.add('active');publicSession.innerHTML=`<a href="expediente/index.html"><span>SESIÓN ACTIVA</span><strong>${publicEscape(displayName)}</strong></a><button id="public-sign-out" type="button">Cerrar sesión</button>`;document.querySelectorAll('.expedient-link').forEach(link=>link.textContent='Volver al Expediente');document.querySelector('#public-sign-out').onclick=async()=>{const client=await getPublicSupabase();await client.auth.signOut();localStorage.removeItem('kizuna-complete');localStorage.removeItem('kizuna-alberto-message-read');clearPublicSession()}};
const checkRemoteCompletion=async()=>{try{const client=await getPublicSupabase();const {data:{session}}=await client.auth.getSession();if(!session){clearPublicSession();return}publicUser=session.user;const [{data,error},{data:profile,error:profileError}]=await Promise.all([client.from('expedient_progress').select('state').eq('user_id',session.user.id).maybeSingle(),client.from('expedient_profiles').select('display_name').eq('id',session.user.id).maybeSingle()]);if(profileError)console.warn('No se pudo recuperar el nombre del usuario.',profileError);showPublicSession(session.user,profile);if(error)return;publicProgressState=data?.state||null;if(!data?.state?.completed){localStorage.removeItem('kizuna-complete');localStorage.removeItem('kizuna-alberto-message-read');document.querySelector('footer p').textContent='Because the best memories deserve to exist.';document.querySelector('#alberto-message-prompt')?.remove();document.querySelector('#alberto-message-link')?.remove();return}localStorage.setItem('kizuna-complete','true');document.querySelector('footer p').textContent='Gracias por haber preservado este recuerdo.';if(data.state.albertoMessageRead===true){localStorage.setItem('kizuna-alberto-message-read','true');enableAlbertoMessage()}else{localStorage.removeItem('kizuna-alberto-message-read');document.querySelector('#alberto-message-link')?.remove();if(!document.querySelector('#alberto-message-prompt'))showAlbertoPrompt()}}catch(error){console.warn('No se pudo consultar el estado del expediente.',error)}};
setTimeout(checkRemoteCompletion,120);

const contactForm=document.querySelector('.contact form');
const normalize=value=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const showContactConfirmation=jose=>{document.querySelector('#contact-confirmation')?.remove();const popup=document.createElement('aside');popup.id='contact-confirmation';popup.setAttribute('role','status');popup.style.cssText='position:fixed;right:24px;bottom:24px;z-index:1000;width:min(420px,calc(100vw - 40px));padding:28px;background:#fffdf8;border:1px solid #b9ad99;box-shadow:12px 14px 32px #1e292733;animation:kizunaPopup .35s ease';popup.innerHTML=`<button aria-label="Cerrar confirmación" id="contact-confirm-close" style="position:absolute;right:12px;top:10px;border:0;background:none;color:#7e1b19;font:22px var(--serif);cursor:pointer">×</button><p style="margin:0 25px 16px 0;font:600 25px/1.05 var(--serif);color:var(--red)">Gracias por contactar con KIZUNA Travel Bureau.</p><p style="font-size:12px;line-height:1.7">Hemos recibido tu consulta correctamente.</p><p style="font-size:12px;line-height:1.7">Uno de nuestros especialistas se pondrá en contacto contigo lo antes posible.</p><p style="margin:21px 0 0;font:10px var(--mono);letter-spacing:.06em">Número de referencia: KTB-INQ-2026-0148</p>${jose?'<p id="associated-search" style="margin:18px 0 0;color:#7e1b19;font:10px var(--mono);letter-spacing:.06em">Buscando expedientes asociados...</p>':''}`;document.body.appendChild(popup);popup.querySelector('#contact-confirm-close').onclick=()=>popup.remove();const search=popup.querySelector('#associated-search');if(search)setTimeout(()=>{search.style.transition='opacity .35s';search.style.opacity='0';setTimeout(()=>search.remove(),360)},1000)};
const showTemporalEasterEgg=()=>{const overlay=document.createElement('div');overlay.innerHTML='<div style="width:min(480px,88vw);padding:48px;background:#efe4cf;color:#202726;box-shadow:14px 14px 0 #0005"><p style="margin:0 0 21px;color:#7e1b19;font:10px var(--mono);letter-spacing:.12em">SISTEMA DE GESTIÓN DE EXPEDIENTES</p><h2 id="temporal-message" style="font:600 45px/.95 var(--serif);margin:0">Solicitud detectada.</h2><div style="height:5px;background:#c5b8a0;margin-top:28px"><i id="temporal-bar" style="display:block;width:0;height:100%;background:#7e1b19;transition:width .8s ease"></i></div></div>';overlay.style.cssText='position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;background:rgba(15,27,25,.92);opacity:0;transition:opacity .45s ease';document.body.appendChild(overlay);requestAnimationFrame(()=>overlay.style.opacity='1');const message=overlay.querySelector('#temporal-message'),bar=overlay.querySelector('#temporal-bar');setTimeout(()=>{message.textContent='Verificando protocolo...';bar.style.width='100%'},500);setTimeout(()=>{message.innerHTML='Coincidencia encontrada.<br><br><span style="font:10px var(--mono);letter-spacing:.12em;color:#7e1b19">DEPARTAMENTO RESPONSABLE:</span><br><span style="font-size:34px;color:#7e1b19">División de Archivos Temporales.</span>'},1450);setTimeout(()=>{overlay.style.opacity='0';setTimeout(()=>overlay.remove(),500)},3500)};
const contactButton=contactForm.querySelector('button');
const contactStatus=document.createElement('p');contactStatus.id='contact-submit-status';contactStatus.setAttribute('role','status');contactStatus.style.cssText='min-height:18px;margin:0;color:var(--red);font:10px/1.5 var(--mono)';contactButton.before(contactStatus);
contactButton.addEventListener('click',async()=>{if(!contactForm.checkValidity()){contactForm.reportValidity();return}const nameInput=contactForm.querySelector('input[type="text"]'),emailInput=contactForm.querySelector('input[type="email"]'),messageInput=contactForm.querySelector('textarea'),name=nameInput.value.trim(),email=emailInput.value.trim(),contactMessage=messageInput.value.trim(),jose=normalize(name).includes('jose');if(jose&&contactMessage==='Quiero preservar un recuerdo.'){showTemporalEasterEgg();return}contactButton.disabled=true;contactStatus.textContent='Enviando consulta…';try{const client=await getPublicSupabase();const {error}=await client.from('contact_messages').insert({name,email,message:contactMessage});if(error)throw error;contactForm.reset();contactStatus.textContent='';showContactConfirmation(jose)}catch(error){console.error('No se pudo enviar la consulta.',error);contactStatus.textContent='No se ha podido enviar el mensaje. Inténtalo de nuevo en unos instantes.'}finally{contactButton.disabled=false}});

const openAlbertoLetter=()=>{document.querySelector('#alberto-letter')?.remove();const letter=document.createElement('section');letter.id='alberto-letter';letter.style.cssText='position:fixed;inset:0;z-index:2000;overflow:auto;background:#fffdf8;padding:34px 20px;color:#25221e';letter.innerHTML='<button id="alberto-letter-close" aria-label="Cerrar carta" style="position:fixed;right:24px;top:20px;border:1px solid #8b1d19;background:#fffdf8;color:#8b1d19;padding:10px 14px;font:10px var(--mono);cursor:pointer">Cerrar</button><img src="assets/carta-de-alberto.png" alt="Una carta para ti, de Alberto" style="display:block;width:min(100%,900px);height:auto;margin:10px auto 40px">';document.body.appendChild(letter);document.querySelector('#alberto-letter-close').onclick=()=>letter.remove()};
const enableAlbertoMessage=()=>{if(document.querySelector('#alberto-message-link'))return;const link=document.createElement('a');link.id='alberto-message-link';link.href='#mensaje-alberto';link.textContent='✉ Mensaje de Alberto';link.style.cssText='color:#861816!important;border-bottom:1px solid #861816;padding-bottom:3px';link.onclick=event=>{event.preventDefault();openAlbertoLetter()};document.querySelector('.site-header nav')?.appendChild(link)};
const markAlbertoMessageRead=async()=>{localStorage.setItem('kizuna-alberto-message-read','true');if(!publicSupabaseClient||!publicUser)return;const state={...(publicProgressState||{}),albertoMessageRead:true};publicProgressState=state;const {error}=await publicSupabaseClient.from('expedient_progress').upsert({user_id:publicUser.id,state,updated_at:new Date().toISOString()});if(error)console.warn('No se pudo registrar la lectura del mensaje.',error)};
const showAlbertoPrompt=()=>{const prompt=document.createElement('aside');prompt.id='alberto-message-prompt';prompt.style.cssText='position:fixed;inset:0;z-index:1900;display:flex;align-items:center;justify-content:center;background:rgba(30,41,39,.24);padding:20px';prompt.innerHTML='<div style="width:min(430px,100%);padding:34px;background:#fffdf8;color:#25221e;box-shadow:14px 16px 38px #1e292744"><p style="margin:0 0 20px;color:#861816;font:10px var(--mono);letter-spacing:.12em">NUEVO MENSAJE RECIBIDO</p><h2 style="font:600 43px/.95 var(--serif);margin:0">De: <em style="color:#861816">Alberto</em></h2><p style="margin:26px 0;font:14px/1.7 var(--sans)">Hay un mensaje personal pendiente de lectura.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><button id="alberto-read" style="border:0;background:#861816;color:#fff;padding:14px 17px;font:10px var(--mono);cursor:pointer">Leer mensaje</button><button id="alberto-later" style="border:1px solid #861816;background:transparent;color:#861816;padding:14px 17px;font:10px var(--mono);cursor:pointer">Ahora no</button></div></div>';document.body.appendChild(prompt);document.querySelector('#alberto-read').onclick=()=>{markAlbertoMessageRead();prompt.remove();enableAlbertoMessage();openAlbertoLetter()};document.querySelector('#alberto-later').onclick=()=>prompt.remove()};
